# Generated by Django 2.2 on 2023-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230101_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgry',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='catgry',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
