# Generated by Django 2.2 on 2023-01-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230105_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',)},
        ),
    ]
